### PR TITLE
Pivot: fix the issue that NA case is displayed as 0

### PR DESCRIPTION
**Pull request by hidekoji**
# Description

fix Pivot Calculation for NA value

Before the fix, it shows 0 as a result of aggregation where it should be NA.

image

After the fix.

image

# Checklist
Make sure you have performed following items before submitting this pull request.
If not, please describe the reason.  

- [x] Add test cases for this fix/enhancement
- [x] Pass devtools::check()
- [ ] Pass devtools::test()
- [ ] Test installing from github
- [x] Tested with Exploratory

### CODE REVIEW

**Comment by hideaki** [comment]
I don't think this is an issue. For Number of Rows, 0 makes better default than NA.

**Comment by kanaugust** [comment]
It should be NA because the 'Fill Value' is set to NA.

**Comment by hideaki** [comment]
Argument default should be NA, or fill=NA should be specified explicitly at call from UI.

**Comment by hidekoji** [comment]
changed argument default for fill as NA

**Pull request merged**
